# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Christian Pinedo
tagline:          'Personal Page'
description:      'Blog and information about me to track me on the Internet'
url:              http://chrpinedo.me
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Christian Pinedo'
  url:            https://twitter.com/chrpinedo


plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate:           5
paginate_path:      "/blog/page:num/"

sidebar_blog_link:  "/blog/"

disqus:
  shortname:        chrpinedo

google_analytics:   UA-105717046-1

# Custom vars
#version:            3.4.1
sidebar_home_link:  false
#github:
#  repo:             https://github.com/fongandrew/hydeout

