# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Christian Pinedo
tagline:          'Personal Page'
description:      'Blog and information about me to track me on the Internet'
url:              http://christianpinedo.me
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Christian Pinedo'
  url:            https://twitter.com/chrpinedo

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
#version:            3.4.1
sidebar_home_link:  true
#github:
#  repo:             https://github.com/fongandrew/hydeout

disqus:
  shortname:        chrpinedo

google_analytics:   UA-105717046-1
